### ISSUE TITLE
json с BOM заголовком

### ISSUE THREAD

**Issue by ashfor03** [pepsik-kiev/HTTPAceProxy#1]
похоже распространенная проблема для питона.
json не понимает текст с BOM заголовком и раньше был костыль, какое-то время работало без него...
а в данный момент не могу забрать лист с суперпомойки, говорит что JSON объект не найден.

установленные версии:
python 2.7.14
gevent 1.2.2
psutil 5.4.3
requests 2.18.4
bencode 2.0

с помощью гугла решил вот так :
torrenttelik_plugin.py
```python
            if config.useproxy:
                 req = requests.get(url, headers=headers, proxies=config.proxies, timeout=30)
            else:
                 req = requests.get(url, headers=headers, timeout=10)
            if req.text[0] == u'\ufeff':
                 req.encoding = 'utf-8-sig'
            Torrenttelik.playlist = req.json()

**Comment by pepsik-kiev** [comment]
Сорри .. только сейчас заметил Ваше сообщение. Это не проблема питона. Проблема была на используемом вами "источнике". Там была  отдача заголовков "не в стандарте" https://tools.ietf.org/html/rfc7159#section-8.1  и все было исправлено автором "источника"

**Comment by ashfor03** [comment]
подтверждаю, источник сам исправился.
судя по стандарту, действительно костыль.
можно закрыть, спасибо!
