### ISSUE TITLE
Поддержка DuneHD

### ISSUE THREAD

**Issue by wotan192** [pepsik-kiev/HTTPAceProxy#13]
Из коробки HTTPAceProxy не заработал с Dune 301. После активного гугления разобрался, что Дюна тоже шлет фейковые заголовки, которые нужно отбрасывать. Заработало после добавления в aceconfig.py:

```
        elif useragent == 'DuneHD/1.0' and headers.get('Range') != 'bytes=0-':
            return True
```

Добавьте, пожалуйста, в код, может, сгодится кому

**Comment by pepsik-kiev** [comment]
Added
