### ISSUE TITLE
TorrentFilm PlugIn Test

### ISSUE THREAD

**Issue by aperfeito** [pepsik-kiev/HTTPAceProxy#16]
Hi Pepsik-Kiev,

   I'm opening this issue to show us in practice how to use torrentfilms plugin now with the new improvements in code? Give  an example so you can test here.

Have a nice weekend !

Perfeito, Alexandre

**Comment by pepsik-kiev** [comment]
On the device, create a folder to store torrent files. Specify it in the torrentfilms plugin settings. Сopy there several torrent files that you want to view on it. Next, you call a playlist for viewing in any player
`http://proxy_ip:port/proxyfilms`
оr
`http://proxy_ip:port/films`
In the second case, the built-in proxy in AceEngine is used .....

**Comment by aperfeito** [comment]
pepsik-kiev,

   Huummm .. I did know about it ...  Thanks  !
