### ISSUE TITLE
Можно ли через aceproxy формировать плейлисты с паролями

### ISSUE THREAD

**Issue by keiskar** [pepsik-kiev/HTTPAceProxy#19]
Можно ли как-то научить aceproxy формировать плейлисты с паролями.
В ссылку которую формирует подмешивать пароль в какое-то мeсто например:
http://xx.xx.xx.xx:8081/pid/cid/password:stream.m4a
Или что-то подобное.

**Comment by pepsik-kiev** [comment]
In life, nothing is impossible.
It is necessary to make appropriate changes to the HTTPAceProxy code. The only question is why you need it? What does not fit the built-in firewall functionality?
