### ISSUE TITLE
Web Player Stream

### ISSUE THREAD

**Issue by ainzz** [pepsik-kiev/HTTPAceProxy#24]
Hello,
I am trying to use your aceproxy with a webplayer to watch from my SmartTV which comes only with Opera TV Browser.
What I tried:
```
acestreamtype = http
acestreamtype = hls
```

ffmpeg transcode
` transcodecmd['mp4'] = 'ffmpeg -i - -c:v copy -c:a copy -f mp4 -'.split()
`
All web players (jwplayer, videojs, hslplayer give invalid video format).
From what I saw in the DEBUG messages, acestreamengine outputs m3u8 playlist. Is it possible to use this format to get the stream working?

Thanks! 

**EDIT:** Looks like it's not possible for ffmpeg to transcode to mp4 from STDOUT. Looks like the only solution is to get the m3u8 stream. Any ideas how to do that?

**Comment by pepsik-kiev** [comment]
Proxy output is http progressive download only.  All web players (jwplayer, videojs, hslplayer  etc.) do not support it. You can get m3u8 from AceEngine directly or use on OperaTV this solution - http://ott-play.com/ttv/ ,  just open this link in your browser ....

**Comment by ainzz** [comment]
Thanks for the reply. I got it working using the m3u8 from AceEngine and JWPlayer.
Thanks for the help.
