### ISSUE TITLE
torrenttelik json error and weird messages on terminal

### ISSUE THREAD

**Issue by Digitalone1** [pepsik-kiev/HTTPAceProxy#37]
Hello, from over one month I get this error on terminal when I run aceproxy:

```
torrenttelik_plugin.py [LINE:47  ]# INFO     [02.05 10:11:00] Playlist http://pomoyka.win/trash/ttv-list/ace.json downloaded
torrenttelik_plugin.py [LINE:65  ]# ERROR    [02.05 10:11:00] Can't parse JSON! JSONDecodeError('Expecting value: line 1 column 1 (char 0)')
```

And installing the lastest git I get also those weird messages:

```
b'http://127.0.0.1:6878/hls/c/87000d663d55dafad478ee4dc6ae59c10b4520f1/76549c641800e1f535cf58e0a91c968e/0/60206.ts'
b'http://127.0.0.1:6878/hls/c/87000d663d55dafad478ee4dc6ae59c10b4520f1/76549c641800e1f535cf58e0a91c968e/0/60207.ts'
b'http://127.0.0.1:6878/hls/c/87000d663d55dafad478ee4dc6ae59c10b4520f1/76549c641800e1f535cf58e0a91c968e/0/60208.ts'
b'http://127.0.0.1:6878/hls/c/87000d663d55dafad478ee4dc6ae59c10b4520f1/76549c641800e1f535cf58e0a91c968e/0/60209.ts'
b'http://127.0.0.1:6878/hls/c/87000d663d55dafad478ee4dc6ae59c10b4520f1/76549c641800e1f535cf58e0a91c968e/0/60210.ts'
b'http://127.0.0.1:6878/hls/c/87000d663d55dafad478ee4dc6ae59c10b4520f1/76549c641800e1f535cf58e0a91c968e/0/60211.ts'
b'http://127.0.0.1:6878/hls/c/87000d663d55dafad478ee4dc6ae59c10b4520f1/76549c641800e1f535cf58e0a91c968e/0/60212.ts'
b'http://127.0.0.1:6878/hls/c/87000d663d55dafad478ee4dc6ae59c10b4520f1/76549c641800e1f535cf58e0a91c968e/0/60213.ts'
b'http://127.0.0.1:6878/hls/c/87000d663d55dafad478ee4dc6ae59c10b4520f1/76549c641800e1f535cf58e0a91c968e/0/60214.ts'
b'http://127.0.0.1:6878/hls/c/87000d663d55dafad478ee4dc6ae59c10b4520f1/76549c641800e1f535cf58e0a91c968e/0/60215.ts'
b'http://127.0.0.1:6878/hls/c/87000d663d55dafad478ee4dc6ae59c10b4520f1/76549c641800e1f535cf58e0a91c968e/0/60216.ts'
b'http://127.0.0.1:6878/hls/c/87000d663d55dafad478ee4dc6ae59c10b4520f1/76549c641800e1f535cf58e0a91c968e/0/60217.ts'
b'http://127.0.0.1:6878/hls/c/87000d663d55dafad478ee4dc6ae59c10b4520f1/76549c641800e1f535cf58e0a91c968e/0/60218.ts'
b'http://127.0.0.1:6878/hls/c/87000d663d55dafad478ee4dc6ae59c10b4520f1/76549c641800e1f535cf58e0a91c968e/0/60219.ts'
b'http://127.0.0.1:6878/hls/c/87000d663d55dafad478ee4dc6ae59c10b4520f1/76549c641800e1f535cf58e0a91c968e/0/60220.ts'
b'http://127.0.0.1:6878/hls/c/87000d663d55dafad478ee4dc6ae59c10b4520f1/76549c641800e1f535cf58e0a91c968e/0/60221.ts'
```

Don't know if they are intended to be shown on purpose.

Executed on Arch Linux, latest git installed from AUR package.

**Comment by pepsik-kiev** [comment]
I can not repeat this error in myself. Everything works out as it should. Maybe your IP is blocked on the source with playlists or it has limited access from your domain zone.

**Comment by Digitalone1** [comment]
Okay, but the second error showing transport stream URL does not seem related to IP blocking. I think it's related to something in the latest commits.

And for first error, could you add an error handler to avoid showing those messages? Maybe a try catch statement with an exception on failed json decoding. Thanks.

**Comment by Digitalone1** [comment]
It floods the terminal

![Screenshot_20190505_142034](https://user-images.githubusercontent.com/25790525/57193946-148f3e00-6f41-11e9-9ce5-2f1c85df7c31.png)

**Comment by pepsik-kiev** [comment]
> It floods the terminal

Fixed

**Comment by Digitalone1** [comment]
Thank you. If you can add a try except statement to remove also json decoding error would be very appreciated.

Something like [this](https://www.peterbe.com/plog/jsondecodeerror-in-requests.get.json-python-2-and-3)

**Comment by pepsik-kiev** [comment]
> Something like [this](https://www.peterbe.com/plog/jsondecodeerror-in-requests.get.json-python-2-and-3)

is present in the code and tells you in the proxy log  something like this
`torrenttelik_plugin.py [LINE:65  ]# ERROR    [02.05 10:11:00] Can't parse JSON! JSONDecodeError('Ex`
=)

**Comment by Digitalone1** [comment]
Sorry, I didn't look at the code because I never programmed in Python. I've just did something in javascript and php.

Anyway, I have now understood that I already get that playlist in m3u format from that website, but I didn't know that the domain name was restricted outside Russia. I get it accessing to http://91.92.66.82/trash/ttv-list/ 

Using the plain IP address works to me. Anyway I didn't need it in realty as a plugin, I only reported the issue here because I thought the URL was not working anymore and you forget to update the code. But, if you want, just to make the application more complete, would you add in the except section an attempt to download it from here --> http://91.92.66.82/trash/ttv-list/ace.json if using the domain server fails?

**Comment by sei4eto** [comment]
Hello!
I try to use torrenttelik plugin, but when I try using this request 'http://proxyIP:port/torrenttelik' I've got 'bad request' error message.
What is the proper link I should use?
Thank you!
