### ISSUE TITLE
Acelive and Kodi

### ISSUE THREAD

**Issue by asafemode** [pepsik-kiev/HTTPAceProxy#38]
This link does not work in kodi : http://192.168.1.253:8000/torrent/http%3A%2F%2F91.92.66.82%2Ftrash%2Fttv-list%2Facelive%2Fas_cid_cbe522.acelive/stream.mp4  .  smart tv , mpv and vlc work fine . Maybe you know where the problem is . Thanks .

**Comment by pepsik-kiev** [comment]
Never used KODI. But as far as I know there is an IPTV PVR Simple  in which this link should work without problems

**Comment by asafemode** [comment]
It works good . Thanks.
