### ISSUE TITLE
acestream proxy server broke down

### ISSUE THREAD

**Issue by asafemode** [pepsik-kiev/HTTPAceProxy#39]
Hello , yesterday my acestream proxy server broke down .
Here : [acestream.log](https://pastebin.com/AbBxgjxJ) .
Please help .Thanks.

**Comment by pepsik-kiev** [comment]
`2019-06-02 13:19:00,642|MainThread|acestream|version=3.1.37 code=3013700 revision=f2b78dd date=2019-04-11`

You are using an old version of AceStream. Go to a newer one. Download here - http://t.me/AceStreamMOD 

Versions <3.1.42 require a paid subscription to use

**Comment by asafemode** [comment]
Update acestream to 3.1.44 ARMv7. Work with RaspPi 3 ( Retropie and Kodi ) . Thanks .
