### ISSUE TITLE
HLS

### ISSUE THREAD

**Issue by AlexHighTower** [pepsik-kiev/HTTPAceProxy#4]
Привет

немного не понимаю, что делает опция "streamtype"... если её ставлю на "hls", то судя по всему прокси сам запрашивает у движка не mpegts, а hls, при этом сам всегда отдаёт mpegts..
так и задумано или надо ещё что то менять?

+ второй вопрос, как использовать транскодинг?
выставляю "transcode" в True, а дальше?
пытаюсь в конец ссылки дописать ?fmt=mp2 или /?fmt=mp2 - то всё равно, вижу что пускается ffmpeg который из раздела "default"

**Comment by pepsik-kiev** [comment]
1) Так и задумано. Прокся всегда отдает в mpegts. Так гораздо проще обеспечить одновременный просмотр одного и того же PID разными клиентами одновременно. Да и смысл hls в домашней сети, тем более что оно там НЕ multibitrate и далеко на "адаптивное" ? Просто сделано для того что "вдруг" кто-то не понимает что движок все тот же mpegts нарезает на куски и очень хочет получать от движка поток в HLS + есть нюанс с "источниками" . Если источник в hls -то на выходе движка всегда hls. Как пример архивы TTV. 
2) А в aceconfig.py при этом присутствует что-то типа
transcodecmd['mp2'] = 'ffmpeg -i - -c:a mp2 -c:v mpeg2video -f mpegts -qscale:v 2 -'.split()
Иначе откуда проксе знать что такое /?fmt=mp2 ?

**Comment by pepsik-kiev** [comment]
Я понял когда у Вас не отрабатывается /fmt= , скорее всего Вы вызываете "напрямую"
что-то типа /content_id/xxxxxxxxxxxxx/?fmt=  или /infohash/xxxxxxxxxxxxx/?fmt= Верно ?

**Comment by AlexHighTower** [comment]
1. эх... а я уж размечтался...
смысл лично для меня - поясню: дома поднят движок с проксей и смотрю не только дома, но бывает и на даче включу, да и друзьям открыл доступ... соответственно при нестабильном инете между клиентов до сервера, hls ведёт себя лучше, т.к. плеер кеширует несколько чанков и их играет, подгружая данные "вперёд"... тот hls что отдаёт сам движок, лично по моим наблюдениям, ведёт себя достойно. опять таки, в моей ситуации и моих тестах, надо только прозрачно перекидывать m3u8 файлы и в них адреса заменять... ну или я просто ничего не понимаю "в колбасных обрезках" ))))))

2. конфиг по дефолту брал, там эти все настройки есть и как правильно поняли, запрашиваю напрямую через content_id

и тогда уж по транскодингу сразу ещё "замечание" - сейчас если стоит transcode в true, и нет параметра fmt - то будет всегда использоваться транскодинг default, который фактически, в стандартной конфигурации, вызовет ffmpeg, который просто прогонит через себя поток...
и хотелка - чтобы транскодинг был, но только когда явно задан параметр fmt

**Comment by pepsik-kiev** [comment]
1) Прокся кеширует до 8Мбайт потока отдавая на клиента .... это  какой должен быт поганый и-нет чтобы НЕ работало )))) ... Клиент ВСЕГДА получает из кеша . Так что прокся априори подгружает данные вперед , а все клиенты "пасутся" с этих данных. С другой стороны если движок "плохо отдает" , то откуда взяться кешу что в http что в hls?
2) Уже поправил транскодирование и выложил на гит. Проверяйте. На счет хочухи - не проблема на выходных сделаю. Как вариант если не найден соответствующий ключ fmt= то ffmpeg - не запускается ...Подходит?  Сейчас , да, просто запускает "прогон" 1:1 через ffmpeg .

**Comment by AlexHighTower** [comment]
1. как писал выше - могу быть не прав )

2. с последними изменениями вообще не стартует прокся
`Traceback (most recent call last):
  File "./acehttp.py", line 532, in <module>
    ace_pid = findProcess(name)
  File "./acehttp.py", line 451, in findProcess
    proc = [p.info for p in psutil.process_iter(attrs=['pid', 'name']) if name in p.info['name']]
TypeError: process_iter() takes no arguments (1 given)`

**Comment by pepsik-kiev** [comment]
pip install -U psutil

**Comment by AlexHighTower** [comment]
не силён я в питоне и вообще его не пользую....
фишка в том, что до сегодняшних изменений всё работало как часы, а тут проблемы ))
покурил инет, разобрался как удалять ненужное и поставить нужное...
вообщем поехало... буду смотреть дальше!
большое спасибо
