### ISSUE TITLE
Жрёт процессорное время  и память

### ISSUE THREAD

**Issue by hardd2007** [pepsik-kiev/HTTPAceProxy#42]
После просмотра нескольких каналов остаются tcp close_wait соединения на порту, который слушает прокси. При этом сам прокси начинает жрать процессорное время и память пока его не перезапустишь. После перезапуска всё нормально пока не посмотришь какие-нибудь каналы. Логи ведутся если нужно.

**Comment by hardd2007** [comment]
Если просто убить все tcp close_wait, то процессорное время возвращается в норму.

**Comment by pepsik-kiev** [comment]
Логи не нужны. Попробую у себя повторить. Явно "перехимичил" с закрытием сокета при отключении клиента... Попробую проанализировать где "дырка" в коде

**Comment by hardd2007** [comment]
После долгих экспериментов пронаблюдал следующее:
сразу после запуска всё нормально, если не подключаться и ничего не смотреть, может работать часами. Далее при первом подключении  канал показывает нормально, после отключения сокет закрывает. Следующие подключения с вероятностью 80% сокеты не закрываются и в системе остаются tcp close_wait. Чем их больше, тем быстрее со временем начинает жрать процессор и память.
Пробовал и  с python2 и с python3.

**Comment by pepsik-kiev** [comment]
Второй час занимаюсь тем что в разнобой с разных устройств случайным образом щелкаю по каналам . Никаких проблем. Что у Вас в качестве клиентов ?

**Comment by akkyoh** [comment]
У меня в качестве клиентов два телевизор LG, каналы смотрю через Smart IPTV 2.1.56 (https://siptv.app)

**Comment by hardd2007** [comment]
Клиент Android 5.1 iptv pro 5.1.12 (_https://play.google.com/store/apps/details?id=ru.iptvremote.android.iptv.pro). Плейлист сформирован с помойки моим скриптом по описанию примера с помойки.

**Comment by pepsik-kiev** [comment]
Попробуйте , пожалуйста в качестве эксперимента удалить строку socket.close() , она там одна в acehttp.py и проверьте растет ли загрузка проца ?

**Comment by akkyoh** [comment]
> Попробуйте , пожалуйста, в качестве эксперимента, удалить строку socket.close() , она там одна в acehttp.py и проверьте растет ли загрузка проца ?

У себя сделал, завтра вечером отпишусь

**Comment by pepsik-kiev** [comment]
> Клиент Android 5.1 iptv pro 5.1.12 (_https://play.google.com/store/apps/details?id=ru.iptvremote.android.iptv.pro). Плейлист сформирован с помойки моим скриптом по описанию примера с помойки.

Я на этой же прикладнухе + два смарта Samsung тестирую. Не получается повторить

**Comment by tarmets** [comment]
Кстати у меня тоже жрал процессор очень сильно пока я не установил обратно 9 мая Proxy. Теперь всё О'кей!

**Comment by hardd2007** [comment]
> удалить строку socket.close()

Закомментировал. Перезапустил, каналы пощёлкал. close_wait появились. По нагрузке будет видно утром.

**Comment by pepsik-kiev** [comment]
> > удалить строку socket.close()
> 
> Закомментировал. Перезапустил, каналы пощёлкал. close_wait появились. По нагрузке будет видно утром.

`sudo netstat | grep --regexp="127.0.0.1:tproxy" | grep CLOSE_WAIT`

Так смотрите?
