### ISSUE TITLE
Playlist filtering

### ISSUE THREAD

**Issue by gr3m1in** [pepsik-kiev/HTTPAceProxy#45]
Good day,
This is rather a question, not an issue...

I'd like to filter out some whole categories (or "filter in" (keep) only few categories) and leave some matched (against regexp or whatever) channels in remaining categories.

Is there an existing way to use eg. "modules/playlist.py" to perform filtering of playlist entries?
Or maybe there is a proper place to hack this in without massive code disruption?

Thanks in advance!

Kind regards,
gr3m1in

**Comment by pepsik-kiev** [comment]
Yes, you can change the code in "/modules/playlist.py ", in which case it will be a global setting for all playlists. Or change the code of the plugin you need by adding this function to its configuration file. For example, you can change the plugin "/plugins/allfon_plugin.py" and add a parameter as a list of categories to its settings file "/plugins/config/allfon.py". Like black/white list of categories and this will be the local setting applied only to this playlist

**Comment by gr3m1in** [comment]
Will it be correct (from project's design point of view) to follow this approach?
- declare corresponding filtering configuration dict in playlist.py (empty by default)
- add eg. filterItem() to PlaylistConfig() at playlist.py
- declare it as self.filterItem in PlaylistGenerator's init at PlaylistGenerator.py
- use it (if not empty) inside addItem() after all item modifications but before self.itemlist.append to simply skip appending for unwanted entries

**Comment by pepsik-kiev** [comment]
👍

**Comment by gr3m1in** [comment]
The general goal is to prepare childen-friendly playlist.
If you don't mind, I'd like to share some of my thoughts :)

I'm going to do it in a way like linux daemon configuration normally looks.
The configuration should look like a dict (intentionally not an array) with any amount of entries which will be sorted before applied.
Each entry will be of type=whitelist|blacklist and one|both of "channel" and "category" keys with regexp as value.

So desired config should look like this (expressions are just demonstrative):
- 10-adult
- - type=blacklist
- - category=(Erot*, Эрот*, 18+? )
- 20-mult
- - type=wihtelist
- - category=(Entert*, Child*, Kids)
- - channel=(Cartoon*, Disney*, 2x2*)
- 30-cognitive
- - type=whitelist
- - category=(Educat*, Познав*)
- - channel=(Discovery*, Nat(ional)?\s?Geo(graphic)?)
...
- 99-default
- - type=blacklist
- - channel(*,)

and so on, having the config structured and easily updatable.

The default action may be done by simply adding the very last entry with corresponding type and greedy wildcard as category/channel.

Constructive critic is deeply appreciated :)

**Comment by gr3m1in** [comment]
Hi,
I've implemented the filtering as described above, tested it on my side, and now would propose the changes to your project.
Please see the attachment
[filtering.diff.txt](https://github.com/pepsik-kiev/HTTPAceProxy/files/4746369/filtering.diff.txt)

**Comment by pepsik-kiev** [comment]
Hi !Send pull request I am merge sources and I will add a description of this functionality on the AceHTTPproxy forum
