### ISSUE TITLE
What its the Problem ??

### ISSUE THREAD

**Issue by aperfeito** [pepsik-kiev/HTTPAceProxy#6]
Downloading https://files.pythonhosted.org/packages/13/de/ba92335e9e76040ca7274224942282a80d54f85e342a5e33c5277c7f87eb/greenlet-0.4.13.tar.gz (58kB)
    100% |████████████████████████████████| 61kB 2.9MB/s 
Installing collected packages: greenlet, gevent
  Running setup.py install for greenlet ... done
  Running setup.py install for gevent ... done
Successfully installed gevent-1.3.1 greenlet-0.4.13
You are using pip version 9.0.3, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
[aperfeito@alarm HTTPAceProxy]$ sudo pip install --upgrade pip
Collecting pip
  Downloading https://files.pythonhosted.org/packages/0f/74/ecd13431bcc456ed390b44c8a6e917c1820365cbebcb6a8974d1cd045ab4/pip-10.0.1-py2.py3-none-any.whl (1.3MB)
    100% |████████████████████████████████| 1.3MB 376kB/s 
Installing collected packages: pip
  Found existing installation: pip 9.0.3
    Uninstalling pip-9.0.3:
      Successfully uninstalled pip-9.0.3
Successfully installed pip-10.0.1
[aperfeito@alarm HTTPAceProxy]$ sudo pip install psutil
Collecting psutil
  Downloading https://files.pythonhosted.org/packages/14/a2/8ac7dda36eac03950ec2668ab1b466314403031c83a95c5efc81d2acf163/psutil-5.4.5.tar.gz (418kB)
    100% |████████████████████████████████| 419kB 4.0MB/s 
Installing collected packages: psutil
  Running setup.py install for psutil ... done
Successfully installed psutil-5.4.5
[aperfeito@alarm HTTPAceProxy]$ sudo python acehttp.py --prefix=/usr/local/
  File "acehttp.py", line 343
    old_umask = os.umask(077)
                           ^
SyntaxError: invalid token
[aperfeito@alarm HTTPAceProxy]$ 

Linux alarm 3.10.18-24-ARCH #1 SMP Wed Nov 29 16:27:21 PST 2017 armv7l GNU/Linux

How correct to run your application ?

**Comment by pepsik-kiev** [comment]
Try in the python interpreter (I check on arm & mipsel based devices)
```
Linux localhost 3.10.0 #1 SMP PREEMPT Tue Sep 20 12:56:05 CEST 2016 aarch64
Python 2.7.13 (default, Nov 24 2017, 17:33:09) 
[GCC 6.3.0 20170516] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> old_umask = os.umask(077)
>>> old_umask
18
>>> 
```

```
Linux Keenetic_Ultra 3.4.113 #1 SMP Sat May 19 13:14:27 MSK 2018 mips GNU/Linux
Python 2.7.15 (default, May 13 2018, 14:20:15) 
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> old_umask = os.umask(077)
>>> old_umask
18
>>> 

```
May be you have something messed up with the rights permissions ?

**Comment by pepsik-kiev** [comment]
O! Do NOT use SUDO =) You need 
```
./python acehttp.py
```
If you want start "from" sudo add user name to aceconfig.py
```
    # If started as root, drop privileges to this user.
    # Leave empty to disable.
    aceproxyuser = ''
```

**Comment by aperfeito** [comment]
First i using the engine from acestream-armv7]$ sudo ./acestream.start from this repo 

https://github.com/sshmanko/acestream-armv7

And works fine look the reply in firefox:

mycallback({"result": {"code": 3013000, "platform": "android", "version": "3.1.30"}, "error": null});

Now I see this in your aceconfig.py

# You need to set it only on Linux based systems. Autodetect for Windows!
    acecmd = "acestreamengine --client-console --live-buffer 25 --vod-buffer 10 --vod-drop-max-age 120"

I not using acestreamengine i using [aperfeito@alarm acestream-armv7]$ sudo ./acestream.start

with this values :  

After I did the changes on aceproxyuser = aperfeito

[aperfeito@alarm HTTPAceProxy]$ ./acehttp.py
Traceback (most recent call last):
  File "./acehttp.py", line 7, in <module>
    import gevent
ImportError: No module named gevent
[aperfeito@alarm HTTPAceProxy]$ sudo python acehttp.py
  File "acehttp.py", line 343
    old_umask = os.umask(077)
                           ^
SyntaxError: invalid token
[aperfeito@alarm HTTPAceProxy]$ python acehttp.py
  File "acehttp.py", line 343
    old_umask = os.umask(077)
                           ^
SyntaxError: invalid token
[aperfeito@alarm HTTPAceProxy]$ ./python acehttp.py
bash: ./python: No such file or directory
[aperfeito@alarm HTTPAceProxy]$ sudo ./acehttp.py
Traceback (most recent call last):
  File "./acehttp.py", line 7, in <module>
    import gevent
ImportError: No module named gevent
[aperfeito@alarm HTTPAceProxy]$

**Comment by aperfeito** [comment]
Help me https://github.com/pepsik-kiev/HTTPAceProxy/issues/6#issuecomment-391463290

**Comment by aperfeito** [comment]
YES Working --- Under Python 2 

acehttp.py           [LINE:463 ]# DEBUG    [23.05 17:11:29]  Ace Stream HTTP Proxy server IP: 172.27.60.210 autodetected
acehttp.py           [LINE:469 ]# INFO     [23.05 17:11:29]  Ace Stream HTTP Proxy server starting .....
acehttp.py           [LINE:470 ]# DEBUG    [23.05 17:11:29]  Using python 2.7.15
acehttp.py           [LINE:471 ]# DEBUG    [23.05 17:11:29]  Using gevent 1.2.2
acehttp.py           [LINE:472 ]# DEBUG    [23.05 17:11:29]  Using psutil 5.4.5
acehttp.py           [LINE:473 ]# DEBUG    [23.05 17:11:29]  Using requests 2.18.4
acehttp.py           [LINE:474 ]# DEBUG    [23.05 17:11:29]  Using bencode 2.0
acehttp.py           [LINE:515 ]# INFO     [23.05 17:11:29]  Remote Ace Stream engine found on 127.0.0.1:6878
acehttp.py           [LINE:534 ]# INFO     [23.05 17:11:29]  Load Ace Stream HTTP Proxy plugins .....
acehttp.py           [LINE:542 ]# DEBUG    [23.05 17:11:29]  Plugin loaded: Torrenttv
acehttp.py           [LINE:542 ]# DEBUG    [23.05 17:11:29]  Plugin loaded: P2pproxy
acehttp.py           [LINE:542 ]# DEBUG    [23.05 17:11:29]  Plugin loaded: Stat
acehttp.py           [LINE:542 ]# DEBUG    [23.05 17:11:29]  Plugin loaded: Torrenttelik
acehttp.py           [LINE:542 ]# DEBUG    [23.05 17:11:29]  Plugin loaded: Torrentfilms
acehttp.py           [LINE:542 ]# DEBUG    [23.05 17:11:29]  Plugin loaded: Allfon
acehttp.py           [LINE:548 ]# INFO     [23.05 17:11:29]  Server started at 172.27.60.210:8000 Use <Ctrl-C> to stop
