### ISSUE TITLE
How to Run ?

### ISSUE THREAD

**Issue by aperfeito** [pepsik-kiev/HTTPAceProxy#7]
1o. Step OK

[aperfeito@alarm ~]$ vlc -I telnet --clock-jitter -1 --network-caching -1 --sout-mux-caching 2000 --telnet-password admin
VLC media player 4.0.0-dev Otto Chriek (revision 4.0.0-dev-827-gcda6b57532)
shared memfd open() failed: Function not implemented
[b8637cf0] main playlist: playlist is empty
[b866ebf0] [telnet] lua interface: Listening on host "telnet://:4212".

2o. Step OK Acestream Engine OK

http://127.0.0.1:6878/webui/api/service?method=get_version&format=jsonp&callback=mycallback
mycallback({"result": {"code": 3013000, "platform": "android", "version": "3.1.30"}, "error": null});

3o. Step HHTPAceProxy OK

[aperfeito@alarm HTTPAceProxy]$ sudo python2 acehttp.py
[sudo] password for aperfeito: 
acehttp.py           [LINE:463 ]# DEBUG    [23.05 17:53:56]  Ace Stream HTTP Proxy server IP: 172.27.60.210 autodetected
acehttp.py           [LINE:469 ]# INFO     [23.05 17:53:56]  Ace Stream HTTP Proxy server starting .....
acehttp.py           [LINE:470 ]# DEBUG    [23.05 17:53:56]  Using python 2.7.15
acehttp.py           [LINE:471 ]# DEBUG    [23.05 17:53:56]  Using gevent 1.2.2
acehttp.py           [LINE:472 ]# DEBUG    [23.05 17:53:56]  Using psutil 5.4.5
acehttp.py           [LINE:473 ]# DEBUG    [23.05 17:53:56]  Using requests 2.18.4
acehttp.py           [LINE:474 ]# DEBUG    [23.05 17:53:56]  Using bencode 2.0
acehttp.py           [LINE:515 ]# INFO     [23.05 17:53:56]  Remote Ace Stream engine found on 127.0.0.1:6878
acehttp.py           [LINE:534 ]# INFO     [23.05 17:53:56]  Load Ace Stream HTTP Proxy plugins .....
acehttp.py           [LINE:542 ]# DEBUG    [23.05 17:53:56]  Plugin loaded: Torrenttv
acehttp.py           [LINE:542 ]# DEBUG    [23.05 17:53:56]  Plugin loaded: P2pproxy
acehttp.py           [LINE:542 ]# DEBUG    [23.05 17:53:56]  Plugin loaded: Stat
acehttp.py           [LINE:542 ]# DEBUG    [23.05 17:53:56]  Plugin loaded: Torrenttelik
acehttp.py           [LINE:542 ]# DEBUG    [23.05 17:53:56]  Plugin loaded: Torrentfilms
acehttp.py           [LINE:542 ]# DEBUG    [23.05 17:53:56]  Plugin loaded: Allfon
acehttp.py           [LINE:548 ]# INFO     [23.05 17:53:56]  Server started at 172.27.60.210:8000 Use <Ctrl-C> to stop

4o Step

How to run this  //9eba690be925a98e8aecfc758070b874e19260c6 acestream pid in vlc

Thanks

**Comment by pepsik-kiev** [comment]
1 Step VLC - an extra step and it is not needed in "server"-side
2 Step AceStream - you can do "inside" proxy =) Just change in aceconfig.py 
```
acespawn=True
acecmd= /path/to/your/acestream.start (I see that you are using my rework of AceStream Engine for
``` ARM)
3. OK
4. Anywhere on the local network on the computer start VLC and type 
http://proxy_ip:port/content_id/blablablablablablablablablablablablablabla/stream.mp4
for example
http://192.168.1.35:8081/9eba690be925a98e8aecfc758070b874e19260c6/stream.mp4

p.s. Read please my conversation with **WolfganP** - https://github.com/pepsik-kiev/HTTPAceProxy/issues/5

**Comment by aperfeito** [comment]
Hi This is update about : 
[aperfeito@alarm HTTPAceProxy]$ sudo python2 acehttp.py
[sudo] password for aperfeito: 
```
acehttp.py           [LINE:463 ]# DEBUG    [24.05 13:21:37]  Ace Stream HTTP Proxy server IP: 172.27.60.210 autodetected
acehttp.py           [LINE:469 ]# INFO     [24.05 13:21:37]  Ace Stream HTTP Proxy server starting .....
acehttp.py           [LINE:470 ]# DEBUG    [24.05 13:21:37]  Using python 2.7.15
acehttp.py           [LINE:471 ]# DEBUG    [24.05 13:21:37]  Using gevent 1.3.1 ---> Look
acehttp.py           [LINE:472 ]# DEBUG    [24.05 13:21:37]  Using psutil 5.4.5
acehttp.py           [LINE:473 ]# DEBUG    [24.05 13:21:37]  Using requests 2.18.4
acehttp.py           [LINE:474 ]# DEBUG    [24.05 13:21:37]  Using bencode 2.0
acehttp.py           [LINE:515 ]# INFO     [24.05 13:21:37]  Remote Ace Stream engine found on 127.0.0.1:6878
acehttp.py           [LINE:534 ]# INFO     [24.05 13:21:37]  Load Ace Stream HTTP Proxy plugins .....
acehttp.py           [LINE:542 ]# DEBUG    [24.05 13:21:37]  Plugin loaded: Torrenttv
acehttp.py           [LINE:542 ]# DEBUG    [24.05 13:21:37]  Plugin loaded: P2pproxy
acehttp.py           [LINE:542 ]# DEBUG    [24.05 13:21:37]  Plugin loaded: Stat
acehttp.py           [LINE:542 ]# DEBUG    [24.05 13:21:37]  Plugin loaded: Torrenttelik
acehttp.py           [LINE:542 ]# DEBUG    [24.05 13:21:37]  Plugin loaded: Torrentfilms
acehttp.py           [LINE:542 ]# DEBUG    [24.05 13:21:37]  Plugin loaded: Allfon
acehttp.py           [LINE:548 ]# INFO     [24.05 13:21:37]  Server started at 172.27.60.210:8000 Use <Ctrl-C> to stop


```

**Comment by aperfeito** [comment]
Many acestream Links --- Good the server HTTPAceProxy work like this:
``
Accepted connection from 172.27.60.210 path /content_id/02f8a59dd859eb57793ff52c1946a41964837c6b/stream.mp4
acehttp.py           [LINE:98  ]# DEBUG    [24.05 15:09:01]  Headers: {'connection': 'close', 'range': 'bytes=0-', 'accept': '*/*', 'user-agent': 'mpv 0.28.0-139-gdba143de4d', 'host': '172.27.60.210:8000', 'icy-metadata': '1'}
acehttp.py           [LINE:193 ]# WARNING  [24.05 15:09:03]  Create a broadcast "livetv2"
aceclient.py         [LINE:116 ]# DEBUG    [24.05 15:09:03]  >>> START PID 02f8a59dd859eb57793ff52c1946a41964837c6b 0 output_format=http
aceclient.py         [LINE:299 ]# DEBUG    [24.05 15:09:03]  <<< STATE 1
aceclient.py         [LINE:299 ]# DEBUG    [24.05 15:09:03]  <<< STATUS main:starting
aceclient.py         [LINE:299 ]# DEBUG    [24.05 15:09:05]  <<< STATUS main:prebuf;0;0;0;0;0;0;0;0;0;0;0;0
aceclient.py         [LINE:299 ]# DEBUG    [24.05 15:09:07]  <<< STATUS main:prebuf;0;0;0;0;0;0;0;0;0;0;0;0
aceclient.py         [LINE:299 ]# DEBUG    [24.05 15:09:09]  <<< STATUS main:prebuf;0;0;0;0;0;0;0;0;0;0;0;0
aceclient.py         [LINE:299 ]# DEBUG    [24.05 15:09:11]  <<< STATUS main:prebuf;0;0;0;0;0;0;0;0;0;0;0;0
aceclient.py         [LINE:299 ]# DEBUG    [24.05 15:09:13]  <<< STATUS main:prebuf;0;0;0;0;0;0;0;0;0;0;0;0
aceclient.py         [LINE:299 ]# DEBUG    [24.05 15:09:15]  <<< STATUS main:prebuf;0;0;0;0;0;0;0;0;0;0;0;0
aceclient.py         [LINE:299 ]# DEBUG    [24.05 15:09:17]  <<< STATUS main:prebuf;0;0;0;0;0;0;0;0;0;0;0;0
aceclient.py         [LINE:299 ]# DEBUG    [24.05 15:09:19]  <<< STATUS main:prebuf;0;0;0;0;0;0;0;0;0;0;0;0
aceclient.py         [LINE:299 ]# DEBUG    [24.05 15:09:21]  <<< STATUS main:prebuf;0;0;0;0;0;0;0;0;0;0;0;0
aceclient.py         [LINE:299 ]# DEBUG    [24.05 15:09:23]  <<< STATUS main:prebuf;0;0;0;0;0;0;0;0;0;0;0;0
aceclient.py         [LINE:299 ]# DEBUG    [24.05 15:09:25]  <<< STATUS main:prebuf;0;0;0;0;0;0;0;0;0;0;0;0
aceclient.py         [LINE:299 ]# DEBUG    [24.05 15:09:27]  <<< STATUS main:prebuf;0;0;0;0;0;0;0;0;0;0;0;0
aceclient.py         [LINE:299 ]# DEBUG    [24.05 15:09:29]  <<< STATUS main:prebuf;0;0;0;0;0;0;0;0;0;0;0;0
aceclient.py         [LINE:299 ]# DEBUG    [24.05 15:09:31]  <<< STATUS main:prebuf;0;0;0;0;0;0;0;0;0;0;0;0
aceclient.py         [LINE:199 ]# ERROR    [24.05 15:09:33]  Engine response time exceeded. GetURL timeout!
acehttp.py           [LINE:79  ]# ERROR    [24.05 15:09:33]  AceClient exception: AceException('Engine response time exceeded. GetURL timeout!',)
aceclient.py         [LINE:116 ]# DEBUG    [24.05 15:09:33]  >>> EVENT stop
aceclient.py         [LINE:116 ]# DEBUG    [24.05 15:09:33]  >>> STOP
aceclient.py         [LINE:299 ]# DEBUG    [24.05 15:09:33]  <<< STATE 0
acehttp.py           [LINE:216 ]# WARNING  [24.05 15:09:33]  Broadcast "livetv2" stoped. Last client disconnected
aceclient.py         [LINE:299 ]# DEBUG    [24.05 15:09:33]  <<< STATUS main:idle
 ``

**Comment by aperfeito** [comment]
The only link i found to work  HTTPAceProxy show this below
`acehttp.py           [LINE:97  ]# INFO     [24.05 17:30:27]  Accepted connection from 172.27.60.210 path /content_id/084d7d071cc1ff3d7d24a3af663389c56e8ed74e/stream.mp4
acehttp.py           [LINE:98  ]# DEBUG    [24.05 17:30:27]  Headers: {'connection': 'close', 'range': 'bytes=0-', 'accept': '*/*', 'user-agent': 'mpv 0.28.0-139-gdba143de4d', 'host': '172.27.60.210:8000', 'icy-metadata': '1'}
acehttp.py           [LINE:193 ]# WARNING  [24.05 17:30:27]  Create a broadcast "FOX Spain"
aceclient.py         [LINE:116 ]# DEBUG    [24.05 17:30:27]  >>> START PID 084d7d071cc1ff3d7d24a3af663389c56e8ed74e 0 output_format=http
aceclient.py         [LINE:299 ]# DEBUG    [24.05 17:30:27]  <<< STATE 1
aceclient.py         [LINE:299 ]# DEBUG    [24.05 17:30:27]  <<< STATUS main:starting
aceclient.py         [LINE:299 ]# DEBUG    [24.05 17:30:29]  <<< STATUS main:prebuf;0;0;0;0;0;0;0;0;0;0;0;0
aceclient.py         [LINE:299 ]# DEBUG    [24.05 17:30:29]  <<< EVENT livepos last=-1 live_first=-1 pos=-1 first_ts=0 last_ts=0 is_live=1 live_last=-1 buffer_pieces=3
aceclient.py         [LINE:299 ]# DEBUG    [24.05 17:30:31]  <<< START http://127.0.0.1:6878/content/cbaf58476da025586b7cefec3d5036850a9375d9/0.694081136486 stream=1
aceclient.py         [LINE:204 ]# DEBUG    [24.05 17:30:31]  Open video stream: http://127.0.0.1:6878/content/cbaf58476da025586b7cefec3d5036850a9375d9/0.694081136486
aceclient.py         [LINE:209 ]# DEBUG    [24.05 17:30:31]  Get headers from client: {'connection': 'close', 'accept': '*/*', 'user-agent': 'mpv 0.28.0-139-gdba143de4d', 'host': '172.27.60.210:8000', 'icy-metadata': '1'}
acehttp.py           [LINE:204 ]# WARNING  [24.05 17:30:31]  Broadcast "FOX Spain" created
acehttp.py           [LINE:211 ]# INFO     [24.05 17:30:31]  Streaming "FOX Spain" to 172.27.60.210 started
aceclient.py         [LINE:299 ]# DEBUG    [24.05 17:30:31]  <<< STATE 2
aceclient.py         [LINE:116 ]# DEBUG    [24.05 17:30:31]  >>> EVENT play
acehttp.py           [LINE:286 ]# DEBUG    [24.05 17:30:31]  Sending HTTPAceProxy headers to client: {'Connection': 'Keep-Alive', 'Content-Type': 'None', 'Keep-Alive': 'timeout=15, max=100'}
aceclient.py         [LINE:299 ]# DEBUG    [24.05 17:30:31]  <<< STATUS main:prebuf;50;0;0;0;0;0;0;0;0;0;0;0
aceclient.py         [LINE:299 ]# DEBUG    [24.05 17:30:31]  <<< EVENT livepos last=1208 live_first=1029 pos=1030 first_ts=1527206423 last_ts=1527208231 is_live=0 live_last=1208 buffer_pieces=3

**Comment by pepsik-kiev** [comment]
Read carefully again my conversation with **WolfganP**, where I explain that the PID changes regularly and in case when the PID is no longer working you'll see  STATUS messages from AceAngine in proxy log like
```
<<< STATUS main:prebuf;0;0;0;0;0;0;0;0;0;0;0;0
```
Please read AceStream documentation to understand what's what - http://wiki.acestream.org/wiki/index.php/Engine_API/en
p.s. There I gave a link where you can get always fresh PIDs .....

**Comment by aperfeito** [comment]
Hi pepsik , How are you. I thinsk you had a good world cup

   I update my Httproxy from here and now every PID or content_id i put the proxy give this error:

`acehttp.py           [LINE:193 ]# WARNING  [16.06 11:38:30]  Create a broadcast "57f897d8c8dd2c32312384f3a2b62c63e82601c0"
aceclient.py         [LINE:117 ]# DEBUG    [16.06 11:38:30]  >>> START PID 57f897d8c8dd2c32312384f3a2b62c63e82601c0 0 output_format=http
acehttp.py           [LINE:77  ]# ERROR    [16.06 11:38:40]  AceClient exception: AceException('gevent_Timeout',)
aceclient.py         [LINE:117 ]# DEBUG    [16.06 11:38:40]  >>> EVENT stop`

**Comment by aperfeito** [comment]
HI pepsik-kiev,

  Yes go step forward update code implementation in  Phython 3 version !!!! 

Great

Cheers

**Comment by aperfeito** [comment]
Python2 and Python3 test as same code take from here look:

```
[aperfeito@alarm HTTPAceProxy]$ python acehttp.py
acehttp.py           [LINE:442 ]# INFO     [05.08 13:57:19]  Ace Stream HTTP Proxy server starting .....
acehttp.py           [LINE:447 ]# DEBUG    [05.08 13:57:20]  Ace Stream HTTP Proxy server IP: 10.181.243.31 autodetected
acehttp.py           [LINE:492 ]# INFO     [05.08 13:57:20]  Remote Ace Stream engine found on 127.0.0.1:6878
acehttp.py           [LINE:511 ]# INFO     [05.08 13:57:20]  Load Ace Stream HTTP Proxy plugins .....
acehttp.py           [LINE:519 ]# DEBUG    [05.08 13:57:20]  Plugin loaded: Torrenttv
acehttp.py           [LINE:519 ]# DEBUG    [05.08 13:57:20]  Plugin loaded: P2pproxy
acehttp.py           [LINE:519 ]# DEBUG    [05.08 13:57:20]  Plugin loaded: Stat
acehttp.py           [LINE:519 ]# DEBUG    [05.08 13:57:20]  Plugin loaded: Torrenttelik
acehttp.py           [LINE:519 ]# DEBUG    [05.08 13:57:20]  Plugin loaded: Torrentfilms
acehttp.py           [LINE:519 ]# DEBUG    [05.08 13:57:20]  Plugin loaded: Allfon
acehttp.py           [LINE:525 ]# INFO     [05.08 13:57:20]  Server started at 10.181.243.31:8000 Use <Ctrl-C> to stop
^CKeyboardInterrupt
2018-08-05T21:00:17Z
acehttp.py           [LINE:418 ]# INFO     [05.08 14:00:17]  Shutdown server.....
acehttp.py           [LINE:422 ]# INFO     [05.08 14:00:17]  Bye Bye .....
[aperfeito@alarm HTTPAceProxy]$ python2 acehttp.py
acehttp.py           [LINE:442 ]# INFO     [05.08 14:00:23]  Ace Stream HTTP Proxy server starting .....
acehttp.py           [LINE:447 ]# DEBUG    [05.08 14:00:23]  Ace Stream HTTP Proxy server IP: 10.181.243.31 autodetected
acehttp.py           [LINE:492 ]# INFO     [05.08 14:00:23]  Remote Ace Stream engine found on 127.0.0.1:6878
acehttp.py           [LINE:511 ]# INFO     [05.08 14:00:23]  Load Ace Stream HTTP Proxy plugins .....
acehttp.py           [LINE:519 ]# DEBUG    [05.08 14:00:23]  Plugin loaded: Torrenttv
acehttp.py           [LINE:519 ]# DEBUG    [05.08 14:00:23]  Plugin loaded: P2pproxy
acehttp.py           [LINE:519 ]# DEBUG    [05.08 14:00:23]  Plugin loaded: Stat
acehttp.py           [LINE:519 ]# DEBUG    [05.08 14:00:23]  Plugin loaded: Torrenttelik
acehttp.py           [LINE:519 ]# DEBUG    [05.08 14:00:23]  Plugin loaded: Torrentfilms
acehttp.py           [LINE:519 ]# DEBUG    [05.08 14:00:23]  Plugin loaded: Allfon
acehttp.py           [LINE:525 ]# INFO     [05.08 14:00:23]  Server started at 10.181.243.31:8000 Use <Ctrl-C> to stop
```

**Comment by pepsik-kiev** [comment]
> I download this playlist as.direct.m3u (AceSearch) in my computer 
You don't need HTTPAceProxy for this playlist . It work directly on VLC . Just start VLC -> File -> Open network -> and type - http://91.92.66.82/trash/ttv-list/as.direct.m3u

**Comment by aperfeito** [comment]
Hi pepski-kiev,

   Yes, I thought I needed AceProxy with a plugin for this to work and I was having a hard time finding the solution

Cheers

Have a nice weekend !
