### ISSUE TITLE
Phython versions transition 2 to Phyton 3

### ISSUE THREAD

**Issue by aperfeito** [pepsik-kiev/HTTPAceProxy#8]
`When` I using Phython 2 everyting fly BUT when you try to use phyton version 3 like below things changes:

Python 3.6.5 (default, May 15 2018, 23:28:47) 
[GCC 8.1.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> exit ()
[aperfeito@alarm ~]$ 

1o. issue resolved:
[aperfeito@alarm HTTPAceProxy]$ sudo python acehttp.py
[sudo] password for aperfeito: 
  
`File` "acehttp.py", line 343
    old_umask = `os.umask(077)

I change `for` `os.umask('077')`
Works for Both Phyton2 run no problems and Python 3 either BUT 

`[aperfeito@alarm` HTTPAceProxy]$ sudo python acehttp.py
Traceback (most recent call last):
  File "acehttp.py", line 19, in <module>
    import aceclient
  File "/home/aperfeito/Downloads/HTTPAceProxy/aceclient/__init__.py", line 2, in <module>
    from acemessages import *
ModuleNotFoundError: No module named 'acemessages' ``

I think if you have time you can improve the code tor running in Phyton 3 also I had gevent 1.3 installed

PS: I have limitation in know about programing in Phyton 3 but i help all i can here

Thanks

**Comment by pepsik-kiev** [comment]
You CAN'T use py3 with this version of HTTPAceProxy. For py3 the HTTPAceProxy code need finalization & optimization. I have ver. of HTTPAceProxy for Py3 
```
acehttp.py           [LINE:703 ]# INFO     [24.05 11:24:06]  Ace Stream HTTP Proxy server starting ....
acehttp.py           [LINE:704 ]# INFO     [24.05 11:24:06]  Using python 3.6.2
acehttp.py           [LINE:705 ]# INFO     [24.05 11:24:06]  Using gevent 1.3
acehttp.py           [LINE:706 ]# INFO     [24.05 11:24:06]  Using psutil 5.4.6
acehttp.py           [LINE:707 ]# INFO     [24.05 11:24:06]  Using requests 2.18.4
acehttp.py           [LINE:708 ]# INFO     [24.05 11:24:06]  Using bencode 2.0
acehttp.py           [LINE:776 ]# DEBUG    [24.05 11:24:06]  Plugin loaded: Torrenttelik
acehttp.py           [LINE:776 ]# DEBUG    [24.05 11:24:06]  Plugin loaded: Stat
acehttp.py           [LINE:776 ]# DEBUG    [24.05 11:24:07]  Plugin loaded: P2pproxy
acehttp.py           [LINE:776 ]# DEBUG    [24.05 11:24:07]  Plugin loaded: Allfon
acehttp.py           [LINE:776 ]# DEBUG    [24.05 11:24:07]  Plugin loaded: Torrenttv
acehttp.py           [LINE:776 ]# DEBUG    [24.05 11:24:07]  Plugin loaded: Torrentfilms
acehttp.py           [LINE:783 ]# INFO     [24.05 11:24:07]  Server started and waiting for requests at 192.168.2.1:8000
```
But this ver. only for my personal use and I did not post it .... let's wait the time when Python 3 becomes the standard and support for Python 2 will be terminated

**Comment by aperfeito** [comment]
Ok Thanks !!!
