### ISSUE TITLE
Little explanation

### ISSUE THREAD

**Issue by aperfeito** [pepsik-kiev/HTTPAceProxy#9]
As you comment before

```
p.s.

/content_id/
/infohash/
/url/
/data/         
/direct_url/  
/efile_url/
```

/conteni_id Its about content_id himself acestream links
/infohash its about the infohash of file you wanna watch  using acestream engine

How I use for files .acelive 

Could give a example for 4 left below

/url/
/data/         
/direct_url/  
/efile_url/

Thanks

**Comment by pepsik-kiev** [comment]
```
http://proxy_ip:port/url/_urlencode_acelive_file_/stream.mp4
http://192.168.1.50:8000/url/http%3A%2F%2Fpomoyka.lib.emergate.net%2Ftrash%2Fttv-list%2Facelive%2Falf_cid_6245c8.acelive/stream.mp4
```
/data/_the contents of the transport file in base64_/stream.mp4
/direct_url/_a direct http-link to the content (for playback without a transport file)_/stream.mp4
/efile_url/_link to the acemedia file (an encrypted media file that can be played using ACE Stream software)_/stream.mp4

The last two you will never find on the Internet  ;)

**Comment by aperfeito** [comment]
Nice ! Thanks
